### ISSUE TITLE
Active Agents/Customers cannot be retrieved

### ISSUE THREAD

**Issue by k0478git** [houspi/otrs-zabbix-stat#1]
The Items Active Agents and Active Customers cannot be retrieved.
Error in zabbix_agent.log is
"Can't locate object method "GetActiveSessions" via package "Kernel::System::AuthSession" at /opt/otrs/bin/otrs.ZabbixStat.pl line 92"

System is: OTRS 5.0.13
Debian 9.6
Perl 5.24

Zabbix 4.0.3

**Comment by houspi** [comment]
Well,
looks like you're using the old version of OTRS 5.
There is really no GetActiveSessions method.
I'll think about how to get around this.

**Comment by k0478git** [comment]
Ok, thanks for your answer. Guess that I'll have to upgrade then ;)

**Comment by houspi** [comment]
I have fixed it.

**Comment by k0478git** [comment]
> I have fixed it.

Works like a charm. Thanks a lot!
