### ISSUE TITLE
Closed tickets and Created tickets not work

### ISSUE THREAD

**Issue by strannick-ru** [houspi/otrs-zabbix-stat#3]
```
/opt/otrs/bin/otrs.ZabbixStat.pl statetype Closed
[Thu Mar 14 13:46:05 2019] otrs.ZabbixStat.pl: Use of uninitialized value $rv in concatenation (.) or string at /opt/otrs/bin/otrs.ZabbixStat.pl line 58.
```

**Comment by strannick-ru** [comment]
```
sub GetStatByStateType {
…
    if ( @TicketIDs == 0 ) { @TicketIDs = (0); }  ##  ← fix
    return $TicketIDs[0];
```

**Comment by houspi** [comment]
>  if ( @TicketIDs == 0 ) { @TicketIDs = (0); }
I think this check is not needed here.
When I call the TicketSearch function I use COUNT as the result type.
So, the @TicketIDs array will always contain one element with the number of tickets found.

**Comment by houspi** [comment]
> /opt/otrs/bin/otrs.ZabbixStat.pl statetype Closed
> [Thu Mar 14 13:46:05 2019] otrs.ZabbixStat.pl: Use of uninitialized value $rv in concatenation (.) or string at /opt/otrs/bin/otrs.ZabbixStat.pl line 58.

What version of OTRS are you using?
